### PR TITLE
Fix unsplit mode in control panel

### PR DESCRIPTION
**Pull request by z-jun**

### CODE REVIEW

**Comment by tahvane1** [comment]
@mattsaxon What you think about this?

**Comment by mattsaxon** [comment]
Well I use unsplit mode, so am not sure what it is fixing. My view is that I wouldn't approve such a PR without a linked issue where we can debate the symptoms and proposed logical fix to it..... perhaps one exists but I can't see it referenced

**Comment by tahvane1** [comment]
#159

**Comment by mattsaxon** [comment]
Actually I apologies, my system is in partial mode (JA80CentralUnit.SYSTEM_MODE_PARTIAL), so this has no impact on me and I can't test it.

Looks a fairly reasonable change to me though looking at the code. I'd argue to merge

**Pull request merged**
